### ISSUE TITLE
`boxen` module gives error

### ISSUE THREAD

**Issue by ziyaddin** [charlespeters/inspire-cli#5]
Hello,

After executing `inspire` command several times, I got this error:

```bash
$ inspire
/home/ziyaddin/.npm-global/lib/node_modules/inspire-cli/node_modules/boxen/index.js:119
		marginLeft = PAD.repeat(padWidth);
		                 ^

RangeError: Invalid count value
    at String.repeat (native)
    at module.exports.middle (/home/ziyaddin/.npm-global/lib/node_modules/inspire-cli/node_modules/boxen/index.js:119:20)
    at formatQuote (/home/ziyaddin/.npm-global/lib/node_modules/inspire-cli/cli.js:28:32)
    at quote (/home/ziyaddin/.npm-global/lib/node_modules/inspire-cli/cli.js:36:15)
    at inspire (/home/ziyaddin/.npm-global/lib/node_modules/inspire-cli/cli.js:46:3)
    at Object.<anonymous> (/home/ziyaddin/.npm-global/lib/node_modules/inspire-cli/cli.js:56:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by charliewilco** [comment]
not really sure how to fix that honestly

**Comment by ziyaddin** [comment]
It seems it is directly related with `boxen` module.
